# Generated by Django 2.1 on 2019-04-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
