# Generated by Django 2.1 on 2019-04-30 03:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
